Add multiple connections to redis pub/sub
LGP21-LGP5/quizz-websocket-redis pull request #3
Opened 2021-05-26 23:03 UTC by andrefmrocha

2021-05-27 09:04 UTC, gmtorres requested changes
First time it happened, at least from a long time that I don't see an error on the go server, but I leave the logs here, I will try to find what is missing
![image](https://user-images.githubusercontent.com/36744231/119798184-cf952600-bed2-11eb-964b-94280efb4768.png)

2021-05-27 09:17 UTC, andrefmrocha commented
> First time it happened, at least for a long time that I don't see an error on the go server, but I leave the logs here, I will try to find what is missing
> ![image](https://user-images.githubusercontent.com/36744231/119798184-cf952600-bed2-11eb-964b-94280efb4768.png)

I think the redis connection is reading for all kinds of messages, I need to make that more simple :thinking: . Will look into it today during the afternoon

2021-05-27 09:37 UTC, andrefmrocha commented
@gmtorres let me know how it works now!

2021-05-28 15:52 UTC, PedroHugoNoevo approved these changes
I am a simple man. I see that it works, I approve.

2021-05-28 17:52 UTC, bernas670 approved these changes
Lgtm!

2026-03-20 17:23 UTC, closed without merging